[package]
name = "tetra-mac"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
num = "0.4.3"
num-derive = "0.4.2"
num-complex = "0.4.6"
num-traits = "0.2.19"
log = "0.4.27"
env_logger = "0.11.8"

